default_platform(:ios)

platform :ios do
  lane :test do
    commit = last_git_commit
    changelog = commit[:message]
    UI.message "更新记录: #{changelog}"

    changelog = changelog_from_git_commits(
      commits_count: 2,
      pretty: "- (%ae) %s",
      date_format: "short",
      match_lightweight_tag: false,
      merge_commit_filtering: "exclude_merges"
    )
    UI.message "更新记录: #{changelog}"
  end
end
