name: Merge main branch to dev
on:
  push:
    branches: [ 'main' ]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge main -> dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: dev
          message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.PERSON_ACCESS_TOKEN }}